# Generated by Django 6.0.2 on 2026-03-02 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('turismo', 'Turismo'), ('restaurante', 'Restaurante'), ('hotel', 'Hotel'), ('hospital', 'Hospital'), ('farmacia', 'Farmácia'), ('carregador', 'Carregador Elétrico'), ('outro', 'Outro')], default='turismo', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='roteiros.dia')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roteiros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dia',
            name='roteiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='roteiros.roteiro'),
        ),
    ]
