# Generated by Django 6.0.2 on 2026-06-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='data_viagem',
            field=models.DateField(blank=True, null=True),
        ),
    ]
