# Generated by Django 6.0.2 on 2026-06-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteiros', '0002_roteiro_data_viagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
