# Generated by Django 6.0.2 on 2026-06-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteiros', '0003_roteiro_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='concluida',
            field=models.BooleanField(default=False),
        ),
    ]
